// Copyright 2025 skewb1k <skewb1kunix@gmail.com>. Licensed under the MIT License.

// Package golden provides utilities for running "golden" tests in Go.
//
// Golden tests are a technique for verifying that the output of your code
// matches expected results stored in "golden" files. This package automates
// reading input files, comparing their processed output to golden files, and
// updating the golden files.
//
// Directory structure example:
//
//	testdata/
//	  example1.txt
//	  example1.txt.golden
//	  subdir/
//	    example2.txt
//	    example2.txt.golden
//
// All non-golden files under the testdata directory (including subdirectories)
// are treated as test inputs. The corresponding golden file should have the
// same name with a ".golden" suffix.
package golden

import (
	"flag"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

var update = flag.Bool("update", false, "update golden files")

const (
	dir          = "testdata"
	goldenSuffix = ".golden"
)

// Run executes golden tests for all files in the "testdata" directory.
//
// It scans the directory recursively for all regular files that do NOT end with ".golden".
// For each input file, it looks for a corresponding golden file with the same
// name plus the ".golden" suffix.
//
// The provided function `f` is called for each test case with the testing.T,
// the input file content, and the golden file content. Each test runs as a
// subtest named after the input file and is executed in parallel.
//
// If the -update flag is set, golden files will be automatically overwritten
// with the output generated by `f`.
func Run(t *testing.T, f func(t *testing.T, input []byte) []byte) {
	t.Helper()
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		// Skip non-files and golden files
		if !d.Type().IsRegular() || strings.HasSuffix(d.Name(), goldenSuffix) {
			return nil
		}

		name, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}

		t.Run(name, func(t *testing.T) {
			t.Helper()

			input, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}

			goldenPath := path + goldenSuffix
			expected, err := os.ReadFile(goldenPath)
			if err != nil && !*update {
				t.Fatalf("missing golden file for %s: %v", path, err)
			}

			actual := f(t, input)

			if *update {
				if err := os.WriteFile(goldenPath, actual, 0644); err != nil {
					t.Fatalf("updating golden file: %v", err)
				}
				return
			}

			assert.Equal(t, string(expected), string(actual))
		})

		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
}
