package golden

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

var update = flag.Bool("update", false, "update golden files")

const (
	dir          = "testdata"
	goldenSuffix = ".golden"
)

// Run executes golden tests for all files in the "testdata" directory.
//
// It scans the directory for all regular files that do NOT end with ".golden".
// For each input file, it looks for a corresponding golden file with the same
// name plus the ".golden" suffix.
//
// The provided function `f` is called for each test case with the testing.T,
// the input file content, and the golden file content. Each test runs as a
// subtest named after the input file and is executed in parallel.
//
// If the -update flag is set, golden files will be automatically overwritten
// with the output generated by `f`.
func Run(t *testing.T, f func(t *testing.T, input []byte) []byte) {
	t.Helper()
	tests, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}

	for _, test := range tests {
		if !test.Type().IsRegular() || strings.HasSuffix(test.Name(), goldenSuffix) {
			continue
		}

		name := test.Name()
		t.Run(name, func(t *testing.T) {
			t.Helper()
			t.Parallel()
			inputPath := filepath.Join(dir, name)
			goldenPath := inputPath + goldenSuffix

			input, err := os.ReadFile(inputPath)
			if err != nil {
				t.Fatal(err)
			}
			expected, err := os.ReadFile(goldenPath)
			if err != nil && !*update {
				t.Fatalf("missing golden file for %s: %v", inputPath, err)
			}

			actual := f(t, input)

			if *update {
				if err := os.WriteFile(goldenPath, actual, 0644); err != nil {
					t.Fatalf("updating golden file: %v", err)
				}
				return
			}

			assert.Equal(t, string(expected), string(actual))
		})
	}
}
